const typography = {
  h1: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 400,
    fontSize: "96px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "116.70000553131104%",
    textTransform: "none",
  },
  h2: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 400,
    fontSize: "60px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "120.00000476837158%",
    textTransform: "none",
  },
  h3: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "48px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "116.70000553131104%",
    textTransform: "none",
  },
  h4: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "34px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "123.50000143051147%",
    textTransform: "none",
  },
  h5: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "24px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "133.39999914169312%",
    textTransform: "none",
  },
  h6: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "20px",
    letterSpacing: "0.030000001192092896px",
    textDecoration: "none",
    lineHeight: "160.0000023841858%",
    textTransform: "none",
  },
  body1: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 400,
    fontSize: "16px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "150%",
    textTransform: "none",
  },
  body2: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 400,
    fontSize: "14px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "142.99999475479126%",
    textTransform: "none",
  },
  subtitle1: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "16px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "175%",
    textTransform: "none",
  },
  subtitle2: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "14px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "157.00000524520874%",
    textTransform: "none",
  },
  overline: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 400,
    fontSize: "12px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "266.00000858306885%",
    textTransform: "uppercase",
  },
  caption: {
    fontStyle: "normal",
    fontFamily: "Source Sans Pro",
    fontWeight: 600,
    fontSize: "12px",
    letterSpacing: "0px",
    textDecoration: "none",
    lineHeight: "165.9999966621399%",
    textTransform: "none",
  },
};
export default typography;
